name: mathtrainer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  dotenv: ^4.2.0
  english_words: any
  env_variables: ^1.0.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firestore_size: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.4
  gradient_borders: ^1.0.0
  gradient_txt: ^1.0.0
  http: ^1.1.0
  intl: ^0.18.0
  provider: any
  syncfusion_flutter_calendar: ^26.2.7
  syncfusion_flutter_core: ^26.2.8
  timeline_tile: ^2.0.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
