name: mathtrainer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3'

dependencies:
  flutter:
    sdk: flutter
  gradient_borders: ^1.0.0
  gradient_txt: ^1.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.3
  syncfusion_flutter_calendar: ^26.2.7

  english_words: any
  provider: any
  firebase_database: ^10.4.0
  env_variables: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
